#!/bin/bash

welcome() {
   trap "error_handler" ERR

   ## No progress bar if automatically started,
   ## dispatching the progress bar in that case is the task
   ## of --showx.
   if [ "$AUTOSTARTED" = "1" ]; then
      return 0
   fi

   ## No progress meter, if timesync was run by cron.
   if [ "$SCRIPTNAME" = "timesync" ]; then 
      if [ "$RUN_BY_CRON" = "1" ]; then
         return 0
      fi
   fi
   
   TITLE="$SCRIPTNAME $VM $INSTALLED_WHONIX_VERSION Info $(date)"

   $output ${output_opts[@]} --progressbar --title "$TITLE" --message "$NOTIFY_MSG" --parentpid "$$" &
}

