#!/bin/bash

trap_sigterm() {
   rm --force "/var/run/whonix/whonixcheck/"$SCRIPTNAME"_running"
   rm --force "/var/run/whonix/whonixcheck/"$SCRIPTNAME"_waiting"
   rm --force "/var/run/whonix/whonixcheck/"$SCRIPTNAME"_pid"
   
   echo "$SCRIPTNAME: SIGTERM received. Exiting."
   exit 0
}

trap "trap_sigterm" SIGTERM

cleanup() {
   trap "error_handler" ERR

   true "cleanup function..."

   $output ${output_opts[@]} --progress "100"
 
   rm --force "/var/run/whonix/whonixcheck/"$SCRIPTNAME"_running"
   rm --force "/var/run/whonix/whonixcheck/"$SCRIPTNAME"_waiting"
   rm --force "/var/run/whonix/whonixcheck/"$SCRIPTNAME"_pid"
   
   touch "/var/run/whonix/whonixcheck/"$SCRIPTNAME"_done"
  
   sync
   
   ## Close pipe, which was opened for zenity.
   #exec 3>&- || true

   if [ "$AUTOSTARTED" = "1" ]; then
      true
   else
      true
      # manual run
      #$output ${output_opts[@]} --showx
      ##$output ${output_opts[@]} --showcli
   fi
   
   cd ..
   #if [ -d "$VERIFY_TEMPDIR" ]; then
      #rm -r "$VERIFY_TEMPDIR"
   #fi
  
   ## default exit code
   if [ "$EXIT_CODE" = "" ]; then
      EXIT_CODE="0"
   fi

   if [ "$1" = "1" ]; then
      true "END"
      exit "$EXIT_CODE"
   fi
}
