#!/bin/bash

#set -x

## TODO: UNFINISHED!

SCRIPTNAME="$(basename $0)"

#source /usr/lib/whonix/whonixcheck/help_error-handler
#source /usr/lib/whonix/whonixcheck/17_check_tor_enabled
#source /usr/lib/whonix/whonixcheck/67_check_clock
#source /usr/lib/whonix/whonixcheck/70_check-sdwdate

#check_tor_enabled

#check_bootclockrandomization

#check_timesanitycheck

#run_timesanitycheck

